### ISSUE TITLE
OAuth 2.0 support in zoom-api

### ISSUE THREAD

**Issue by utter-step** [oxidecomputer/cio#1]
Hi! Thanks for the great crates pack :)

I'm looking for the library to abstract away interaction with Zoom API, and your crate looks like what I need!
There is one detail though: my Zoom App is [OAuth 2.0 App](https://marketplace.zoom.us/docs/guides/build#understanding-app-types), and it looks like currently your lib supports only JWT-apps.

Is it possible to consider adding some option to allow OAuth 2.0 as well?
It looks like to do so we just need a possibility to provide OAuth access token during the creation of `Zoom` struct, instead of jwt key and secret.

I'd be glad to be of any help if you consider this feature worthy!

**Comment by jessfraz** [comment]
Contributions welcome! I would take a look at some of the Google API's in
this directory using oauth2 for a reference if that helps!

**Comment by gevorgyana** [comment]
Hi guys, is it still relevant?

**Comment by jessfraz** [comment]
this is now moved to https://github.comoxidecomputer/third-party-api-clients as it is generated and there is oauth 2.0 support.

closed.
