### ISSUE TITLE
huddle calendar updates not working

### ISSUE THREAD

**Issue by wesolows** [oxidecomputer/cio#12]
I've tried to figure out why this is happening and cannot.  My GSuite calendar has recurring host boot huddle entries far into the future; they seem like they should match the fuzzy string from configs.  However, the airtable calendar (https://airtable.com/tblb9ACUfEopO5Rx2/viwbDtmYCWzUF8EEO?blocks=bipLfQLiV0dJ5dXRC) has past meetings, then a meeting that I canceled via GSuite, and then the next (and only) meeting listed is July 20.  From looking at the code, I would expect to see 13 weeks worth of future meetings automatically populated.  Not surprisingly, this also makes it impossible to submit an agenda item for any other meeting date.  This has been the same for over a week, so the regular jobs to update huddles aren't fixing it.  As none of the diagnostic printfs from the crate end up in the job output and the cargo test used to do this population requires things I don't have to run (right?), I'm not sure how to debug this.

**Comment by jessfraz** [comment]
Yeah so this was what I was saying to Sean in the PR he made to change it to 13 weeks, basically Gsuite is only giving me 1 week into the future even if I request more. I need to code in a work around just it's a bit lower on my priority list

**Comment by jessfraz** [comment]
Basically since GSuite is doing that I need to do the math for the next events myself which is annoying but doable but not something I can bite off right away

**Comment by wesolows** [comment]
I see.  That still doesn't seem to explain why the one on July 13 isn't showing up (and the one for today that I canceled wasn't there yesterday either).  But I'll try creating them manually in airtable for now until the GSuite thing is working.

**Comment by jessfraz** [comment]
Yeah that is weird

**Comment by jessfraz** [comment]
closing as now this appears to work much better
