### ISSUE TITLE
Preview page prior to application?

### ISSUE THREAD

**Issue by wright-joe** [oxidecomputer/cio#6]
In regards to [applicants.rs](https://github.com/oxidecomputer/cio/blob/master/cio/src/applicants.rs), I am curious if specialized formatting is preserved during read_pdf()'s extraction.  Would a preview page prior to the submit be worthwhile?

**Comment by jessfraz** [comment]
not really we accept submissions through google forms so we don't have control there to show a preview. the main point of the functionality is parsing text not formatting, its used for search, nothing else.
